volumes:
  go:
  vue:

networks:
  local:
  traefik:
    external: true
  jetstream:
    external: true

services:
  gw:
    image: jrgensen/gateway
    platform: linux/x86_64
    environment:
      PROXY_MAPPINGS: >
        hq:ui
        mysql:adminer:8080
        redis:redis-commander:8081
    networks:
    - local
    - traefik
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.hq.rule: Host(`hq.dev.nathejk.dk`) || Host(`hq.local.nathejk.dk`) || HostRegexp(`.+\.hq\..+\.nathejk\.dk`)

  ui:
    build:
      context: .
      target: ui-dev
      dockerfile: docker/Dockerfile
        #entrypoint: ["sleep", "infinity"]
    volumes:
    - ./vue:/app
    - vue:/app/node_modules
    environment:
      DEBUG: "true"
      NODE_ENV: development
      AUTH_BASEURL: https://lukmigind.nathejk.dk
      API_BASEURL: http://api.hq.dev.nathejk.dk
    depends_on:
    - gw
    networks:
    - local

  api:
    build:
      context: .
      target: api-dev
      dockerfile: docker/Dockerfile
    #entrypoint: /app/docker/bin/init-dev
    #command: api
    volumes:
    - ./go:/app
    - go:/go
    networks:
    - local
    - jetstream
    environment:
      #GO_BUILD_FLAGS: -race
      JETSTREAM_DSN: nats://dev.nathejk.dk:4222
      DB_DSN: root:ib@tcp(mysql:3306)/hq?parseTime=true
      SMS_DSN: cpsms://TOKEN@api.cpsms.dk
      #REDIS_ADDR: redis:6379
      #MONOLITH_BASEURL: https://natpas.nathejk.dk
      JWT_COOKIE_NAME: jwttoken
      AUTH_BASEURL: https://lukmigind.nathejk.dk
    depends_on:
    - gw
    #- redis
    - mysql

  mysql:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: ib
      MYSQL_DATABASE: hq
      MYSQL_USER: nathejk
      MYSQL_PASSWORD: kodeord
      TZ: Europe/Copenhagen
    networks:
    - local

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DEFAULT_USER: nathejk
      ADMINER_DEFAULT_PASSWORD: kodeord
      ADMINER_DEFAULT_DB: hq
    networks:
    - local
    depends_on:
    - gw
    - mysql

#  redis:
#    image: redis:4.0-alpine3.8
#    entrypoint: redis-server --appendonly yes
#    networks:
#    - local
#
#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    platform: linux/x86_64
#    environment:
#      REDIS_HOSTS: auth:redis:6379
#    networks:
#    - local

